# -*- coding: utf-8 -*-
"""labtask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpnULODLB1hA4TvO3_fQ7Uubz2KxsvzM
"""

number=[22,33,44,55]
print(number)

fruits=('apple','banana','cherry','mango')
print('Second element:',fruits[1])
print('Last element:',fruits[-1])

#convert tuple to list
fruit_list=list(fruits)
fruit_list[2]='orange'
print('modified list:',fruit_list)

"""5. **SET:**"""

name1={'Ali','Asad','Abdullah','Ishaq'}
name2={'Abdullah','Ishaq','Aleeza','Nabia','Rimsha'}
print('union:',name1|name2)
print('Intersection:',name1&name2)
print('Difference:',name1-name2)
name1.add('javeria')
name2.remove('Ismaeel')
print('Updated name1',name1)
print('Updated name2',name2)

"""DICTIONARY:"""

student_marks = {
    "Aleena": 85,
    "Biqtash": 92,
    "Chaman": 78,
    "Dolly": 90,
    "Eiman": 88
}
print('keys:',student_marks.keys())
print('values:',student_marks.values())
print('items:',student_marks.items())

print(student_marks)

student_marks={
    "ali":20,
      "ali":21,
      "ali":22,
  "ali":23,
      "ali":24,
}
print(student_marks)